language: java

jdk:
  - openjdk8

script: mvn --settings .travis/settings.xml clean  verify

deploy:
  -
    provider: script
    script: .travis/deploy.sh
    skip_cleanup: true
    on:
      repo: idealo/deckard
      tags: true
      jdk: openjdk8

notifications:
  email:
    - opensource-deckard@idealo.de