language: java

jdk:
  - openjdk8

before_install:
  - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
  - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust

install: mvn --settings travis/settings.xml install -DskipTests=false -Dgpg.skip -Dmaven.javadoc.skip=true -B -V

deploy:
  -
    provider: script
    script: bash .travis/deploy.sh
    cleanup: false
    on:
      branch: master
      tags: true
      jdk: openjdk8


notifications:
  email:
    - opensource-deckard@idealo.de