language: java

jdk:
  - openjdk8

script: mvn --settings .travis/settings.xml clean  verify

deploy:
  -
    provider: script
    script: bash .travis/deploy.sh
    cleanup: false
    on:
      branch: master
      tags: true
      jdk: openjdk8


notifications:
  email:
    - opensource-deckard@idealo.de