name: Delete specific package version

on:
  push:
    branches: [ master ]
  
jobs:
  delete:
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Delete package
      - uses: actions/delete-package-versions@v1
        with:
          package-version-ids: '1.0.3-RELEASE'
